### ISSUE TITLE
How can i use a mpv.conf with the libmpv in sfvip player? 

### ISSUE THREAD

**Issue by aries1998** [sebdelsol/sfvip-all#11]
Just try to find a way to enable hardware decoder in  libmpv .   
1 Tried to add "config-dir" in libmpv.json but app seems reset the file content when start.
2 Tried make libmpv.json readonly after modified ,  then app just won't start .

**Comment by sebdelsol** [comment]
* `libmpv.json` is just meant to store the current _mpv dll_ version and is not supposed to be modified by the user. 
* `mpv.conf` is the mpv configuration file that should be in _Sfvip Player_ directory (where you'll find it's _exe_).
