### ISSUE TITLE
misleading description feature...

### ISSUE THREAD

**Issue by p060477** [sebdelsol/sfvip-all#4]
hi, in this repo is written:
Sfvip all : "Insert an All category so you can easily search your entire catalog."...
but it is not true...cause also if i start sfvip player, i mean not yr launcher sfvip all 1.4.12 
but the salezi sfvip player  i also have the -all- caregory to be search
....so this is not a unique feature of yr repo sfvip all item...isn't it...??

**Comment by sebdelsol** [comment]
Please read carefully: All category into Live, **Series and Vod**.
Sfvip Player has an All category for the channels since **only** after 1.2.5.7 
A it's is still missing an all category for vod & series.
Cheers

**Comment by p060477** [comment]
> Please read carefully: [...] inserts an All category into Live, **Series and Vod**. Sfvip Player has an All category for the channels since **only** after 1.2.5.7 And it's still missing an all category for vod & series as of today. It comes in handy when you have thousands of those... Cheers

You have to write -watch carefully-...cause what is written is very clearly..:
"Insert an All category so you can easily search your entire catalog."
i have only copy paste what you have written....
only if we see careffully the IMAGE we see the circler across vod and series....
but this is not really very easely to understand.....
i suggest you to correct mainly what you have written...:
from:
""Insert an All category so you can easily search your entire catalog."
to:
**"Insert an All category in thre VOD AND SERIES  so you can easily search your entire catalog."**

am i wrong...??!!... ;)

**Comment by sebdelsol** [comment]
> am i wrong...??!!... ;)

Yes: Sfvip Player has no All category for the channels in 1.2.5.7.
And some people stick with this version.

**Comment by sebdelsol** [comment]
It's been changed to "Insert an All category when missing ..." in https://github.com/sebdelsol/sfvip-all/commit/d1ea57f76e8b5de548f2fdedb4943676a32b3321

**Comment by p060477** [comment]
hi, hats off to you and yr very kind helping and gentle patience, i really thxs you from the very deep of my heart
i have only a simple question: have you a place where you suggest to find the iptv lists...??...in order to be able to have yr precious sfvip all tool, and of course salezi's sfvip itself, well working..?...is there a site or a place where find them...??
thxs so much in adv
cheers
