### ISSUE TITLE
re-open for suggestion

### ISSUE THREAD

**Issue by p060477** [sebdelsol/sfvip-all#5]
> Please read carefully: [...] inserts an All category into Live, **Series and Vod**. Sfvip Player has an All category for the channels since **only** after 1.2.5.7 And it's still missing an all category for vod & series as of today. It comes in handy when you have thousands of those... Cheers

You have to write **-watch carefully-**...cause what is written is very clear and misleading..:
"Insert an All category so you can easily search your entire catalog."
i have only copy paste what you have written....
only if we see careffully the IMAGE we see the blue circle across vod and series....
but this is not really very easely to understand.....
**i suggest you** to correct mainly what you have written...:
from:
""Insert an All category so you can easily search your entire catalog."
to:
**"Insert an All category in the VOD AND SERIES  so you can easily search your entire catalog."**

am i wrong...??!!... ;)

_Originally posted by @p060477 in https://github.com/sebdelsol/sfvip-all/issues/4#issuecomment-1879802350_

**Comment by sebdelsol** [comment]
Please check https://github.com/sebdelsol/sfvip-all/issues/4#issuecomment-1879901443
