### ISSUE TITLE
how to automatically update sfvip all...??

### ISSUE THREAD

**Issue by p060477** [sebdelsol/sfvip-all#6]
hi there is an option to automatically update sfvip ...but is there also an identic option for yr sfvip all..??...or everytime we have to dl the latest release from this repo on github...??
thxs in adv
cheers

**Comment by sebdelsol** [comment]
The Svip Player auto update works quite randomly (it seems to very rarely check) and it doesn't relaunch the player after an update, so I added one in Sfvip All (you can easily uncheck this option).

**Comment by p060477** [comment]
so how to update sfvip all...??...in sfvip we can go to options and click update now....but this is for sfvip player...but how to for ex pass from yr 1.4.12.6 to latest 1.4.12.8...??...thxs in adv 
cheers

**Comment by sebdelsol** [comment]
![image](https://github.com/sebdelsol/sfvip-all/assets/6039281/0324f0db-1221-42ca-8074-408905bc341a)

**Comment by p060477** [comment]
hi, first thxs, how you do to have this image...??...i when i click yr sfvip all exe get only the sfvip player start....
so how to have this yr image...??
thxs in adv 
cheers

**Comment by sebdelsol** [comment]
hover your mouse hover the pulsing Sfvip All logo at top left of the player:
![image](https://github.com/sebdelsol/sfvip-all/assets/6039281/b165200f-123b-4d5e-9f2f-d89e37b94a14)

**Comment by p060477** [comment]
nice! i really should not be able to imagine...wow...compliments!
a question...: it says libmpv unknown...maybe cause i jhave it but in a portable way.....where should have i to put it in order to be recognized by sfvip all..??
thxs again for yr kind helping!
cheers

**Comment by sebdelsol** [comment]
> a question...: it says libmpv unknown...maybe cause i have it but in a **portable way**.....where should have i to put it in order to be recognized by sfvip all..? ..I mean in which folder it should be better i put it...??

Your _mpv dll_ is in a `lib` folder in the Sfvip Player folder.
At first Sfvip All can't recognize the version since the dll uses a different versioning than the one they use in _mpv_ repo. 

Anyway if you update it (which I recommend) you'll have its version shown.

# To update libmpv:
* Please check libmp auto update. 
It might take some time. be patient sourceforge is sometime very slow. 
* The Sfvip All logo will pulse red to alert you something has to be updated:  
You'll see an install button in the Sfvip all menu. follow the instructions.

**Comment by p060477** [comment]
thxs!...now in the lib folder i've also the old mpv.dll...may i delete it..??...or have i to take it there ...??...it is in a named "old" sub-folder
and about external EPG ...where should i be able to find them...??...and then where should have i to put to be recognized by yr sfvip all?
thxs again for yr kind helping!
cheers

**Comment by sebdelsol** [comment]
> now in the lib folder i've also the old mpv.dll...may i delete it..??...or have i to take it there ...??...it is in a named "old" sub-folder

Those are saved there by Sfvip All as backup in case something goes wrong. You can delete those if you want but there's no need.

> and about external EPG ...where should i be able to find them...??...and then where should have i to put to be recognized by yr sfvip all?

There are lots of external EPG services.  Often providers have an internal EPG, so you'll have nothing to do.
If you are missing channels, you can try with one of [thoses](https://epgshare01.online/epgshare01/).
Be aware that:
* the huge ones (eg. ALL-SOURCES1) has so many channels it takes at least one minute to process.
* the channels' names from your iptv provider and those in the external epg are often different. So I use fuzzy search. 
Hence the confidence level for the EPG: 0% confidence means it'll find less matches but they'll be always correct. 100% confidence means you'll always find a match but that might be the wrong channel. I recommend a value of 30% (the default).

> and the sfvip all log is still pulsing...but now i've all updated...so why...??
* Fast red pulse = something needs your attention
* Green smooth pulse = everything's ok indeed.

**Comment by p060477** [comment]
hi Sebdelsol, thxs so much indeed again!
about iptv lists is there a place or web site you could suggest me to search and find?
thxs so much indeed
cheers

**Comment by sebdelsol** [comment]
> if you see my image attached before you see that sfvip all state: no ext epg...so how to add them...??
    in which folder should have i to put them..to sum up i need a yr small guide to help me to do it....

![image](https://github.com/sebdelsol/sfvip-all/assets/6039281/7f640b6d-b2b3-4bfa-a3d8-24fc4ce6a3ec)

Click on the box you to enter an url. 

> and about iptv lists is there a place or web site you could suggest me to search and find useful ones?

not really.

**Comment by p060477** [comment]
hi and thxs again:

which epg you suggest me to add from the link you gave:
https://epgshare01.online/epgshare01/

and really you do not have a place or site where you find iptv lists...??

thxs so much again

cheers

**Comment by sebdelsol** [comment]
> which ext EPG service you use ?

An XMLTV one: They end up with `.xml` or `.xml.gz`.
On this site they use this pattern : <span>https://</span>epgshare01.online/epgshare01/epg_ripper_**COUNTRY_CODE**.xml.gz
where **COUNTRY_CODE** is US for the usa etc...

> where you search yr iptv lists?

see https://github.com/sebdelsol/sfvip-all/issues/6#issuecomment-1881609753

**Comment by p060477** [comment]
> > which ext EPG service you use ?
> 
> An XMLTV one: They end up with `.xml` or `.xml.gz`. On this site they use this pattern : https://epgshare01.online/epgshare01/epg_ripper_**COUNTRY_CODE**.xml.gz where **COUNTRY_CODE** is US for the usa etc...
> 
> > where you search yr iptv lists?
> 
> see [#6 (comment)](https://github.com/sebdelsol/sfvip-all/issues/6#issuecomment-1881609753)

after the county code there is also a number...mostly is 1...but there are also some has the  2
ex: https://epgshare01.online/epgshare01/epg_ripper_TR2.xml.gz 
or also ...3...4...what they really means...??

2) you develop this beautifull sfvip all project  and you really do not have never tried an iptv list...??
    this is not so believable isn't it...??.....i'm only asking where you search for it...is the same question about epg
    to which you have replied...so where is the difference...??

thxs so much in adv
cheers

**Comment by sebdelsol** [comment]
> after the country code there is also a number...mostly is 1...but there are also some that has the  2
ex: https://epgshare01.online/epgshare01/epg_ripper_TR2.xml.gz 
or also ...3...4...what they really means those numbers after the country code...??

I don't know you'll have to try.

 > iptv list [...] so where is the difference...??

Copyright infringement, that's not the place for those.
