### ISSUE TITLE
Virus sfvip player?

### ISSUE THREAD

**Issue by Trixarn** [sebdelsol/sfvip-all#8]
Why is sfvip player.exe detected as virus? https://www.virustotal.com/gui/file/a96fca90e3c420be71b21b017ffffa27f3a4e60c5355bcf2ac1a53ec6b912ee0

**Comment by sebdelsol** [comment]
A lot of anti virus are lazy and detect anything with build by Nuitka as virus just because some malwares actually uses Nuitka. 

The only way to realistically distribute software nowadays is to buy an EV code signing certificate. It only costs ~500€per year...
Some security providers will even charge you money to whitelist your code. That's their business model.

So that's what it is...

**Comment by p060477** [comment]
the latest  1.4.12.25 is very very worst ...:
https://www.virustotal.com/gui/file/6cfba998d314e3d5226692d3b479c33135cbae35df10c6257a6329d755c92795

->12  RED.....<-

**Comment by p060477** [comment]
**23 security vendors and no sandboxes flagged this file as malicious**
why the olders vers. has really not this very bad score...??...:(

**Comment by sebdelsol** [comment]
Please check https://github.com/sebdelsol/sfvip-all/issues/10#issuecomment-1914278349

**Comment by p060477** [comment]
i have -portabilized- yr installer cause i really do want to use as much portable sw as i can,hope you understand,
so maybe this is the reason of the different md5...and i really do suggest you to offer also a portable way of yr tool....
and i re-suggest you to compile yr tools ,as in the past, in order not to have that so really bad virsutotal score...
sanyway the worst thing is that ALSO my av malwarebytes really do not ALLOW me to use yr tool in the new 1.4.12.25....so this is why i'm trying to make you thinking deeply and carefully about this....
up to now i'm friendly use yr 1.4.12.20...and in my -portable- way....
it is really all up to you if you want yr potentially users be confident in using yr tool
best regards

**Comment by sebdelsol** [comment]
> and i really do suggest you to offer also a portable way of yr tool....

You can build your own portable version as explained [here](https://github.com/sebdelsol/sfvip-all/issues/10#issuecomment-1914354271).

>  i re-suggest you to compile yr tools,as in the past, in order not to have that so really bad virsutotal score...

This has nothing to do with compilation but with the signatures of exes produced by either _Nuitka_ or _Pyinstaller_. 
As it has already been explained both are leveraged by malware creators hence both suffer from lazy AV heuristics. 
Those false positives are so random they often changes on a daily basis.

> it is really all up to you if you want yr potentially users be confident in using yr tool

This repo is freely shared: What people want to do with it is entirely up to them.

> up to now i'm friendly

You keep spamming the issues and now you're quite entitled: I've put a stop to that.
